[package]
name = "solcipher-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-contract = "5.1.1"
casper-types = "5.1.1"

[features]
default = ["casper-contract/std", "casper-types/std"]
